# Generated by Django 4.2.6 on 2023-11-24 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('file', models.FileField(null=True, upload_to='file/')),
                ('is_delay', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='trainee',
            old_name='teacher',
            new_name='trainer',
        ),
        migrations.AddField(
            model_name='notification',
            name='is_approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='trainee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appc.trainee'),
        ),
        migrations.AddField(
            model_name='notification',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appc.trainer'),
        ),
        migrations.CreateModel(
            name='TrainerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('person', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appc.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='TrainerLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('reason', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appc.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='TraineeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('person', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appc.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='TempSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('joindate', models.DateField()),
                ('image', models.ImageField(upload_to='image/')),
                ('degree', models.FileField(upload_to='file/')),
                ('is_special', models.BooleanField(default=False)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appc.course')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appc.department')),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='tempsignup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appc.tempsignup'),
        ),
    ]
