# Generated by Django 4.2.6 on 2023-11-30 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traineenotificationstatus',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='trainernotificationstatus',
            name='department',
        ),
        migrations.RemoveField(
            model_name='trainernotificationstatus',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='tempsignup',
            name='course',
        ),
        migrations.RemoveField(
            model_name='trainee',
            name='course',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='course',
        ),
        migrations.AlterField(
            model_name='trainer',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appc.department'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='TraineeNotificationStatus',
        ),
        migrations.DeleteModel(
            name='TrainerNotificationStatus',
        ),
    ]
