# Generated by Django 4.2.6 on 2023-11-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dateassigned',
            field=models.DateField(),
        ),
    ]
