# Generated by Django 4.2.6 on 2023-11-25 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appc', '0002_alter_project_dateassigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appc.trainer'),
        ),
        migrations.AddField(
            model_name='submitedproject',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appc.trainer'),
        ),
    ]
