# Generated by Django 4.2.6 on 2023-11-22 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appc', '0002_notification_trainee_notification_trainer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainee',
            old_name='teacher',
            new_name='trainer',
        ),
    ]
