# Generated by Django 4.2.6 on 2023-11-25 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appc', '0003_project_trainer_submitedproject_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainernotification',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appc.department'),
        ),
    ]
