# Generated by Django 4.2.6 on 2023-11-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appc', '0004_trainernotification_traineenotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('action', models.BooleanField(default=False)),
                ('file', models.FileField(null=True, upload_to='file/')),
                ('is_delay', models.BooleanField(default=False)),
            ],
        ),
    ]
