# Generated by Django 4.2.6 on 2023-11-23 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appc', '0005_assignedproject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssignedProject',
            new_name='Project',
        ),
    ]
