# Generated by Django 4.2.6 on 2023-11-25 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appc', '0006_alter_trainerleave_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraineeLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('reason', models.TextField()),
                ('is_approved', models.BooleanField(null=True)),
                ('trainee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appc.trainee')),
            ],
        ),
    ]
