# Generated by Django 4.2.6 on 2023-11-23 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appc', '0007_trainerleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerleave',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appc.trainer'),
        ),
    ]
