# Generated by Django 4.2.6 on 2023-11-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appc', '0008_trainerleave_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('link', models.CharField(max_length=255)),
            ],
        ),
    ]
