# Generated by Django 4.2.6 on 2023-11-25 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appc', '0008_traineeleave_is_read_trainerleave_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_schedule',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appc.trainer'),
        ),
    ]
