# Generated by Django 4.2.6 on 2023-11-25 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appc', '0009_class_schedule_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitedproject',
            name='projectcopy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appc.project'),
        ),
    ]
