# Generated by Django 4.2.6 on 2023-11-26 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appc', '0010_submitedproject_projectcopy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appc.department'),
        ),
    ]
