# Generated by Django 4.2.6 on 2023-11-26 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appc', '0011_alter_trainee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appc.trainer'),
        ),
    ]
