# Generated by Django 4.2.6 on 2023-11-26 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appc', '0012_alter_trainee_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appc.trainer'),
        ),
        migrations.AlterField(
            model_name='submitedproject',
            name='projectcopy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appc.project'),
        ),
        migrations.AlterField(
            model_name='tempsignup',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appc.course'),
        ),
        migrations.AlterField(
            model_name='tempsignup',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appc.department'),
        ),
    ]
