# Generated by Django 4.2.6 on 2023-11-26 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appc', '0013_alter_project_trainer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempsignup',
            name='department',
        ),
    ]
