# Generated by Django 4.2.6 on 2023-11-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appc', '0014_remove_tempsignup_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineeleave',
            name='datedifference',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trainerleave',
            name='datedifference',
            field=models.IntegerField(null=True),
        ),
    ]
