# Generated by Django 4.2.6 on 2023-11-28 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appc', '0018_profileedit_trainee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainernotification',
            name='trainer',
        ),
        migrations.AlterField(
            model_name='trainernotification',
            name='forr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appc.trainer'),
        ),
    ]
