# Generated by Django 4.2.6 on 2023-11-28 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appc', '0020_project_forr_alter_submitedproject_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempsignup',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appc.department'),
        ),
        migrations.AlterField(
            model_name='project',
            name='forr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appc.trainee'),
        ),
    ]
